[fmt]
line_length = 100

[profile.default]
solc_version = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = true
extra_output = [
    "metadata",
    "storageLayout",
    "evm.deployedBytecode.immutableReferences",
    "evm.bytecode.opcodes"
]

test = "forge/tests"

libs = [
    "lib",
    "node_modules",
]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "src/=src/",
    "local-modules/=forge/modules/"
]

gas_limit = "18446744073709551615"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options