name: Solana Integration Checks
on:
    push:
        branches:
            - solana/integration
    pull_request: null

env:
    RUSTC_VERSION: 1.76.0
jobs:
    cancel-previous-runs:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                access_token: ${{ github.token }}
    make-lint:
        name: make lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install toolchain
              uses: dtolnay/rust-toolchain@master
              with:
                toolchain: ${{ env.RUSTC_VERSION }}
                components: clippy, rustfmt
            - name: make lint
              run: make lint
              working-directory: ./solana
    make-test:
        name: make test
        runs-on: ubuntu-latest
        # Anchor Docker image: https://www.anchor-lang.com/docs/verifiable-builds#images
        container: backpackapp/build:v0.29.0
        steps:
            - uses: actions/checkout@v4
            - name: Set default Rust toolchain
              run: rustup default stable
              working-directory: ./solana
            - name: make test
              run: make test
              working-directory: ./solana
