name: universal-rs

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'universal/**'

env:
  CARGO_TERM_COLOR: always
  RUSTC_VERSION: 1.75.0

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
      - name: test
        run: cargo test --workspace --all-features
        working-directory: ./universal/rs

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          components: clippy
      - run: cargo clippy --workspace --all-targets
        working-directory: ./universal/rs
        env:
          RUSTFLAGS: -Dwarnings

  docs:
    name: docs
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          components: rust-docs
      - run: cargo doc --workspace --no-deps --document-private-items
        working-directory: ./universal/rs
        env:
          RUSTDOCFLAGS: "--cfg docsrs -D warnings"

  fmt:
    name: fmt
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUSTC_VERSION }}
          components: rustfmt
      - run: cargo fmt --all --check
        working-directory: ./universal/rs